<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputPath>..\1.6\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4104" />
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RimTalk">
      <HintPath>..\..\..\workshop\content\294100\3551203752\1.6\Assemblies\RimTalk.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\1.6\Assemblies\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
